# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - rationalthinkers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_6a989039b0d7467c968002491d9c12ee }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6201c980478c4d46b6c41f8e940a3e5a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_6a989039b0d7467c968002491d9c12ee }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'rationalthinkers'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_83976d28dbff4d7b8b1883eefea61f62 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_6a989039b0d7467c968002491d9c12ee }}/appsvc/staticsite:${{ github.sha }}'